//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pms
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<int> status { get; set; }
        public int owner_id { get; set; }
    }
}
